// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCknQVxRjxI-Aa-f_cLOjPG2njwFqATrgg',
    appId: '1:140127412740:web:7682ddc0a9cff26d5f0b51',
    messagingSenderId: '140127412740',
    projectId: 'zerohuecos',
    authDomain: 'zerohuecos.firebaseapp.com',
    storageBucket: 'zerohuecos.appspot.com',
    measurementId: 'G-7ZH0FKGG02',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHN9KTxiSm4KvFNpBysDlGPiBoOSBjCY4',
    appId: '1:140127412740:android:8794586d837164e85f0b51',
    messagingSenderId: '140127412740',
    projectId: 'zerohuecos',
    storageBucket: 'zerohuecos.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXr6XyTPuroc1XlcHj7xvbQcuzMaxJ_yc',
    appId: '1:140127412740:ios:bd7d52dd2301a21e5f0b51',
    messagingSenderId: '140127412740',
    projectId: 'zerohuecos',
    storageBucket: 'zerohuecos.appspot.com',
    iosBundleId: 'com.example.zerohuecos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXr6XyTPuroc1XlcHj7xvbQcuzMaxJ_yc',
    appId: '1:140127412740:ios:bd7d52dd2301a21e5f0b51',
    messagingSenderId: '140127412740',
    projectId: 'zerohuecos',
    storageBucket: 'zerohuecos.appspot.com',
    iosBundleId: 'com.example.zerohuecos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCknQVxRjxI-Aa-f_cLOjPG2njwFqATrgg',
    appId: '1:140127412740:web:be983482d31f06835f0b51',
    messagingSenderId: '140127412740',
    projectId: 'zerohuecos',
    authDomain: 'zerohuecos.firebaseapp.com',
    storageBucket: 'zerohuecos.appspot.com',
    measurementId: 'G-PQERTGG8MZ',
  );

}